### PR TITLE
CompatHelper: bump compat for KernelAbstractions to 0.9, (keep existi…

### PR DESCRIPTION
**Pull request by milankl**
…ng compat)

### CODE REVIEW

**Comment by milankl** [comment]
@maximilian-gelbrecht I've updated the CUDAKernels and KernelAbstractions compat, however, CI throws this error
```julia
MethodError: no method matching wait(::Nothing)
```
from a test you wrote here
https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/fd30828baaa6ced35e0c23665bc8136f3b02e661/test/kernelabstractions.jl#L18
could you have a look at it?

**Comment by maximilian-gelbrecht** [comment]
Yes, KernelAbstractions v0.9 has a new syntax. I can do a PR on Monday to update the test.

**Comment by milankl** [comment]
> I can do a PR on Monday to update the test.

Just do it here in this PR? I won't merge it anyway before the tests pass

**Comment by maximilian-gelbrecht** [comment]
Ok, will do

**Comment by vchuravy** [comment]
@milankl can you merge #358? It will merge into this branch and should fix your tests.

**Comment by milankl** [comment]
Awesome, thanks Valentin!! We don't actually use it yet, but have started a dependency to test some kernels ... stay tuned!

**Pull request merged**
