### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by milankl** [comment]
Awesome, thanks, there's probably plenty more with all the documentation coming in #348

**Comment by pitmonticone** [comment]
> Awesome, thanks, there's probably plenty more with all the documentation coming in #348

You’re welcome. I’ll take a look at the new docs later to provide a further check. Let me know if you believe it could be useful if I join the organization.

Anyway, congratulations for the package development and maintenance!

**Comment by pitmonticone** [comment]
Done @milankl, just opened the PR #352 to fix typos in new docs.

**Comment by milankl** [comment]
> Let me know if you believe it could be useful if I join the organization. Anyway, congratulations for the package development and maintenance!

Yes absolutely, you're more than welcome to contribute code (and not just typo fixes 😉) I don't know what your background is and what you are particularly interested in, but there's plenty that can be done and I'd be delighted to support any efforts to improve SpeedyWeather.jl Let me know what your thinking and what your capacities are, and I'd be happy to have a call too!

**Comment by pitmonticone** [comment]
Sure, I’ll do it as soon as I find the time to delve deeper in the implementations of this package. Thanks a lot!

**Pull request merged**
