### PR TITLE
Use Temporary Files for Test Output

### PR DESCRIPTION
**Pull request by white-alistair**
@maximilian-gelbrecht since we seem to be talking past each other on the other PR, I thought it would be easier to just show you what I mean here.

In my opinion this is the most correct, clean, and safe way of dealing with files and folders that are created by tests.

Whether you're running the tests locally using `] test` or `include("path_to_test")`, you can run the tests repeatedly without any issues, ensuring that successive test runs are independent.

It also avoids the dangerous use of `rm` on all files matching a certain pattern.

### CODE REVIEW

**Comment by white-alistair** [comment]
@milankl

**Comment by milankl** [comment]
I like this, would probably call that folder `tmp_testruns` to stick to the terminology that a *run* is one simulation which can have several output files

**Comment by white-alistair** [comment]
Before merging I would wait for @maximilian-gelbrecht to confirm this actually solves his problem.

**Comment by white-alistair** [comment]
> One annoying thing though is that `mktempdir` does not work when you kill the process. And in VSCode this is how I end Julia processes usually. Which at least for me, makes this not very useful, and I would still manually remove those folders in the end after all tests.

Just `ctrl + d` the Julia process.

**Comment by maximilian-gelbrecht** [comment]
I really don't get what's wrong with just deleting these temp folders in one line at the end of the test, and then it works in all cases. When the folders are created during the test, then it is definitely save to delete them. `mktempdir` does nothing else when the process is closed.

**Pull request merged**
