### PR TITLE
Docs for `Parameters`

### PR DESCRIPTION
**Pull request by navidcy**
This PR moves the comments in Parameters into proper docstrings using `DocStringExtensions`.

E.g.,

```Julia
julia> using SpeedyWeather

help?> Parameters
search: Parameters ParameterizationConstants

  P = Parameters{M<:ModelSetup}(kwargs...) <: AbstractParameters{M}


  A struct to hold all model parameters that may be changed by the user. The struct uses keywords such that default values can be changed at creation. The default values
  of the keywords define the default model setup.

    •  NF::DataType: number format

    •  trunc::Int64: spectral truncation

    •  Grid::Type{<:SpeedyWeather.RingGrids.AbstractGrid}: grid in use
...
```

and the docs render like:

Screenshot 2023-04-07 at 7 24 22 am

### CODE REVIEW

**Comment by milankl** [comment]
Meaning the documentation can automatically pull the comments on fields in `Parameters`? That would be awesome! Do the docstrings have to be on top of the field?
```julia
"number format"
NF::DataType = DEFAULT_NF
```
would be okay, but not as readable as it is now, I find? Maybe doesn't matter though... 😆

**Comment by navidcy** [comment]
Yeap. Automatically generated!

Docstring need to be on top. We can leave an empty line between each field of Parameters and 2 empty lines between each "section". How does that sound?

**Comment by navidcy** [comment]
(This is also an opportunity to review some of the docs which read a bit vague.)

**Comment by milankl** [comment]
Yes, I'm still on it to group more parameters, for example I would find
```julia
run_speedy(planet=Earth(), atmosphere=StandardAtmosphere(lapse_rate=5), thermodynamics=ThermodynamicParameters(mol_mass_vapour=18))
```
neat. Like who wants to change them anyway. Then just define them as a struct and clear things up in `Parameters`.

**Comment by navidcy** [comment]
This can be a different PR. Feel free to edit as you wish.

**Comment by milankl** [comment]
> This can be a different PR. Feel free to edit as you wish.

I agree this *should* be a different PR, just a heads up that it'll get some sorting anyway, so it won't as crowded!

**Comment by navidcy** [comment]
oooops!
I thought you approved!

**Comment by navidcy** [comment]
oooops!
I thought you approved!

**Comment by navidcy** [comment]
oooops!
I thought you approved!

**Comment by navidcy** [comment]
We can revert! Or open another one?

**Comment by milankl** [comment]
All good, I like this, I'll add better docstrings in future prs!

**Pull request merged**
