### PR TITLE
Corrected adapt functions for Grids, Models, ParameterStructs and SpectralTransform

### PR DESCRIPTION
**Pull request by katharinamaetschke**
I updated the adapt functions for the new Grid files in the way that Milan suggested and also uploaded the Models.jl, Parameter_structs.jl and spectral_transform.jl files again, since I closed the last PR for these.

### CODE REVIEW

**Comment by milankl** [comment]
I don't know whether you want to address this in this pull request, but with #204 and other pull requests mentioned in #192 I'm still actively changing the `Tendencies`, `GridVariables`, `DynamicsVariables`, `SurfaceVariables` structs in `diagnostic_variables.jl`. Just as a heads up.

**Comment by milankl** [comment]
@katharinamaetschke please note #241, the grids are now moved to src/RingGrids in a submodule RingGrids, similar for LowerTriangularMatrix in src/LowerTriangularMatrices and SpeedyTransforms in src/SpeedyTransforms to give everything more structure.

**Comment by milankl** [comment]
@maximilian-gelbrecht is this actually superceded now?

**Comment by maximilian-gelbrecht** [comment]
Yes, let's close it. We have to adjust it to the new structure in another PR.

**Pull request closed without merging**
