### PR TITLE
JOSS paper citation

### PR DESCRIPTION
**Pull request by navidcy**
Just opening this because JOSS is still pointing to the branch. As soon as paper is published we can merge!

### CODE REVIEW

**Comment by navidcy** [comment]
(I should have rebased perhaps so that we only had the last two commits...)

**Comment by milankl** [comment]
Basically the same as long as we squash yeah? Definitely squash otherwise the history is full of various versions of the pdf, enlarging the repo no?

**Comment by navidcy** [comment]
Yes, let's just squash and merge this!

**Comment by navidcy** [comment]
Perhaps before we merge this we should add a `CITATION.cff` file and a [Citing section](https://github.com/CliMA/Oceananigans.jl?tab=readme-ov-file#citing) in the readme and the docs

**Comment by navidcy** [comment]
@milankl have a look and merge if all looks good!

Nice job with the JOSS paper!!!!

**Review by milankl — APPROVED** [review]

**Pull request merged**
