### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by milankl**
Using https://github.com/dangoslen/changelog-enforcer

### CODE REVIEW

**Comment by milankl** [comment]
@maximilian-gelbrecht I copied over this workflow setup from how Makie does it. I thought it might be a good practice to write a few words summary after every PR into a changelog file? Or do you think that would be covered by the "closed pull requests" summary for releases?

**Comment by maximilian-gelbrecht** [comment]
I like it. Good to get an overview of recent changes

**Comment by milankl** [comment]
Not sure whether the workflow should already trigger here?

**Comment by milankl** [comment]
> Not sure whether the workflow should already trigger here?

Haha, I forgot the `.yml` ending, now it works.

**Pull request merged**
