### PR TITLE
Primitive equation dry core bughunt

### PR DESCRIPTION
**Pull request by milankl**

### CODE REVIEW

**Comment by milankl** [comment]
Previous commit resolved the vertical advection bug apparently. Now this 

image

looks like a coslat-scaling error to me.

**Comment by milankl** [comment]
@christophernhill @white-alistair @maximilian-gelbrecht @dmey @hottad @samhatfield  SpeedyWeather.jl primitive equation dry dynamical core is up and running 🎉 60 days at T42 with semi-implicit time integration, surface temperature in the Jablonowski and Williamson testcase

https://user-images.githubusercontent.com/25530332/225746980-297e18d6-3297-4e23-83d2-ceb07af01b7e.mp4

but at higher resolution there are still instabilities, probably just another handful of bugs 😄 T63, 12 levels after 15 days
 
image

**Comment by christophernhill** [comment]
On my birthday too! Must be a good sign, I’ll be in later today.

Happy SpeedyWeather.jl day!

Chris

**Comment by maximilian-gelbrecht** [comment]
I tested a 3-layer setup, like the one I need for my use case currently. 

It only runs when specifying the ZonalRidge orography: 

This works 
```Julia 
p,d,m = SpeedyWeather.initialize_speedy(PrimitiveDryCore, orography=ZonalRidge, zonal_wind_coefs=SpeedyWeather.ZonalWindCoefs(perturb_uₚ=1) ,implicit_α=0, n_days=8, trunc=42, Δt_at_T31=10, σ_levels_half=[0,0.4,0.6,1], run_id="dry-core", output=true)

SpeedyWeather.time_stepping!(p,d,m)
```

This doesn't 
```Julia

p,d,m = SpeedyWeather.initialize_speedy(PrimitiveDryCore, nlev=3, n_days=8, trunc=42, Δt_at_T31=10, σ_levels_half=[0,0.4,0.6,1], run_id="dry-core-2", output=true)

SpeedyWeather.time_stepping!(p,d,m)
```

**Comment by milankl** [comment]
Yes, there are still some stability issues that I'm currently working on. Doesn't surprise me that it blows up (assuming that's what you mean by "doesn't work"). We have a new feature too `debug=true` (default `false`) will tell you when the model blows up by checking the prognostic variables on every time step for non-finite values

**Comment by milankl** [comment]
Still have some stability issues (looks like missing dissipation, bottom drag or similar) but this already is great 👇🏼 

https://user-images.githubusercontent.com/25530332/226691241-0138cf48-5ac6-4f28-9259-e506ddaec873.mp4

**Pull request merged**
